client_id = "f60a7fca2f7d0164558da2fa611a6272"
name = "smart-alert-banner"
application_url = "https://smart-alert-banner-production.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[access_scopes]
scopes = "write_script_tags,read_script_tags"

[auth]
redirect_urls = ["https://smart-alert-banner-production.up.railway.app/auth/callback","https://smart-alert-banner-production.up.railway.app/api/auth/callback"]

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  compliance_topics = ["customers/data_request"]
  uri = "/webhooks/customers/data_request"

  [[webhooks.subscriptions]]
  compliance_topics = ["customers/redact"]
  uri = "/webhooks/customers/redact"

  [[webhooks.subscriptions]]
  compliance_topics = ["shop/redact"]
  uri = "/webhooks/shop/redact"

