# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9e0bbaf4b75c1b59fe25aed45a31cc48"
application_url = "https://smart-alert-banner.onrender.com/app"
embedded = true
name = "smart-alert-banner"

[app_preferences]
url = "https://smart-alert-banner.onrender.com/app/additional"

[access_scopes]
scopes = "read_themes"

[auth]
redirect_urls = [
  "https://smart-alert-banner.onrender.com/auth/callback",
  "https://smart-alert-banner.onrender.com/auth/shopify/callback",
  "https://smart-alert-banner.onrender.com/api/auth"
]

[webhooks]
api_version = "2026-07"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri    = "/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
topics = ["app/scopes_update"]
uri    = "/webhooks/app/scopes_update"

[webhooks.privacy_compliance]
customer_data_request_url = "https://smart-alert-banner.onrender.com/webhooks/customers/data_request"
customer_deletion_url     = "https://smart-alert-banner.onrender.com/webhooks/customers/redact"
shop_deletion_url         = "https://smart-alert-banner.onrender.com/webhooks/shop/redact"


[build]
automatically_update_urls_on_dev = false
