# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f60a7fca2f7d0164558da2fa611a6272"
name = "smart-alert-banner"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
